# Лабораторная работа №5 (Laboratory work 5)
### Построение нейронной сети (сравнение с классификаторами DecisionTree и SVM) - исследование красного вина (Neural network construction (comparison with the classifiers DecisionTree and SVM) - Red Wine Research)

--------------------------------------
### Эпилог (Epilogue):
#### Набор данных относится к красному варианту португальского вина Vinho Verde. Из-за конфиденциальности и логистических проблем доступны только физико-химические (входные данные) и "качество" вина. Также учитываем, что нет дополнительных данных, т.е. о сортах винограда, марке вина, отпускной цене вина и т.д. (The dataset refers to the red variant of the Portuguese wine Vinho Verde. Due to confidentiality and logistical issues, only the physico-chemical (input data) and "quality" of the wine are available. We also take into consideration that there is no additional data, i.e. about grape varieties, wine brand, selling price of wine, etc.)
### Цель (Goal):
#### Данные не стандартизированы, не сбалансированы. Нужно научиться классифицировать данные и сравнить методы: задачу классификации и её после метода главных компонент, сделать вывод о лучшей классификации. (The data is not standardized, not balanced. It is necessary to learn how to classify data and compare methods: the classification task and its main components after the method, to conclude about the best classification.)

-------------------------------------
## Задания 1-2 (Tasks 1-2)
#### Загрузка и анализ исходных данных (Downloading and analyzing input data)

In [23]:
import pandas as pd

In [24]:
df = pd.read_csv('vine.dat', header=None)
df.columns =['FixedAcidity', 'VolatileAcidity', 'CitricAcid', 'ResidualSugar', 'Chlorides', 'FreeSulfurDioxide', 'TotalSulfurDioxide', 'Density', 'PH', 'Sulphates', 'Alcohol', 'Class']
df

,FixedAcidity,VolatileAcidity,CitricAcid,ResidualSugar,Chlorides,FreeSulfurDioxide,TotalSulfurDioxide,Density,PH,Sulphates,Alcohol,Class
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [25]:
print(df['Class'].unique())

[5 6 7 4 8 3]

In [26]:
df['Class'] = df['Class'] - 3
df.dtypes

FixedAcidity          float64
VolatileAcidity       float64
CitricAcid            float64
ResidualSugar         float64
Chlorides             float64
FreeSulfurDioxide     float64
TotalSulfurDioxide    float64
Density               float64
PH                    float64
Sulphates             float64
Alcohol               float64
Class                   int64
dtype: object

-----------------
## Задание 3 (Task 3)
#### Стандартизация (Standardization)

In [27]:
from sklearn import preprocessing
import numpy as np

#### Объявим переменную с названиями всех колонок кроме 'Class' (Declare a variable with the names of all columns except 'Class')

In [28]:
Columns = ['FixedAcidity', 'VolatileAcidity', 'CitricAcid', 'ResidualSugar', 'Chlorides', 'FreeSulfurDioxide', 'TotalSulfurDioxide', 'Density', 'PH', 'Sulphates', 'Alcohol']

In [29]:
scaler_std = preprocessing.StandardScaler()
df[Columns] = scaler_std.fit_transform(df[Columns])
df.dropna()
df

,FixedAcidity,VolatileAcidity,CitricAcid,ResidualSugar,Chlorides,FreeSulfurDioxide,TotalSulfurDioxide,Density,PH,Sulphates,Alcohol,Class
0,-0.528360,0.961877,-1.391472,-0.453218,-0.243707,-0.466193,-0.379133,0.558274,1.288643,-0.579207,-0.960246,2
1,-0.298547,1.967442,-1.391472,0.043416,0.223875,0.872638,0.624363,0.028261,-0.719933,0.128950,-0.584777,2
2,-0.298547,1.297065,-1.186070,-0.169427,0.096353,-0.083669,0.229047,0.134264,-0.331177,-0.048089,-0.584777,2
3,1.654856,-1.384443,1.484154,-0.453218,-0.264960,0.107592,0.411500,0.664277,-0.979104,-0.461180,-0.584777,3
4,-0.528360,0.961877,-1.391472,-0.453218,-0.243707,-0.466193,-0.379133,0.558274,1.288643,-0.579207,-0.960246,2
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,-1.217796,0.403229,-0.980669,-0.382271,0.053845,1.542054,-0.075043,-0.978765,0.899886,-0.461180,0.072294,2
1595,-1.390155,0.123905,-0.877968,-0.240375,-0.541259,2.211469,0.137820,-0.862162,1.353436,0.601055,0.729364,3
1596,-1.160343,-0.099554,-0.723916,-0.169427,-0.243707,1.255161,-0.196679,-0.533554,0.705508,0.542042,0.541630,3
1597,-1.390155,0.654620,-0.775267,-0.382271,-0.264960,1.542054,-0.075043,-0.676657,1.677400,0.305990,-0.209308,2
1598,-1.332702,-1.216849,1.021999,0.752894,-0.434990,0.203223,-0.135861,-0.666057,0.511130,0.010924,0.541630,3

#### Данные стандартизированы и очищены от нулевых значений. (The data is standardized and cleared of zero values.)

-------------------
## Задание 4 (Task 4)
### Разделяем полученный датафрейм на 3 выборки: обучающую, тестовую и валидационную выборки в соотношении 5:3:2 соответственно.

In [30]:
col = ['index'] + Columns + ['Class']

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
train_table, test_valid_table = train_test_split(df, train_size = 0.5)

train_table = train_table.reset_index()
test_valid_table = test_valid_table.reset_index()

df_train_table = pd.DataFrame(train_table, columns = col)
df_test_valid_table = pd.DataFrame(test_valid_table, columns = col)

print('train_table:')
df_train_table

train_table:

,index,FixedAcidity,VolatileAcidity,CitricAcid,ResidualSugar,Chlorides,FreeSulfurDioxide,TotalSulfurDioxide,Density,PH,Sulphates,Alcohol,Class
0,503,1.252685,-1.496173,1.021999,-0.453218,-0.201199,-0.944346,-0.683222,0.452272,-0.849519,2.253421,0.447763,4
1,1279,0.850513,-1.272714,0.611196,-0.595114,-0.541259,-1.231239,-1.139357,-1.031767,-1.108690,-0.520193,1.010966,4
2,1079,-0.241094,-1.272714,2.100359,4.087440,-0.796303,2.068023,7.040655,-1.900989,-1.950996,-0.874272,1.761904,4
3,1346,-1.275249,0.347364,-1.340122,-0.311323,-0.668781,-1.039977,-1.017721,-1.074168,1.353436,-0.579207,0.917099,2
4,1348,-0.643266,0.710485,-1.237421,-0.524166,-0.201199,-0.848716,-1.048130,-0.464652,0.187166,-1.582429,-0.866379,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,750,-0.011282,0.682553,-0.877968,0.256260,0.032592,0.107592,-0.196679,0.680178,-0.136798,-0.638220,-0.866379,2
795,1556,-0.987984,1.967442,-1.186070,-0.240375,-0.456244,-0.370562,-0.804858,-0.204945,1.418228,-0.579207,-0.490910,2
796,948,0.333436,-2.278280,0.919299,-0.524166,-0.264960,-0.561823,-0.774449,-0.650157,0.640715,0.601055,1.386435,4
797,1013,-0.470907,1.017741,-1.391472,-0.666062,0.096353,0.585746,-0.470360,-0.210245,0.446337,-0.461180,-0.397043,3
798,913,0.620701,-0.741999,0.970649,1.462372,0.138860,-1.231239,-1.108948,-0.189045,-0.266384,-0.107102,1.668037,4

#### Тестовая и валидационная выборки находятся в test_valid_table, соответственно тестовая и валидационная относятся друг к другу как 0,6 и 0,4 соответственно.

In [33]:
test_table, valid_table = train_test_split(df_test_valid_table, train_size = 0.6)

test_table = test_table.reset_index()
valid_table = valid_table.reset_index()

df_test_table = pd.DataFrame(test_table, columns = col)
df_valid_table = pd.DataFrame(valid_table, columns = col)

print('test_table:')
df_test_table

test_table:

,index,FixedAcidity,VolatileAcidity,CitricAcid,ResidualSugar,Chlorides,FreeSulfurDioxide,TotalSulfurDioxide,Density,PH,Sulphates,Alcohol,Class
0,1125,0.275983,-1.607903,0.405794,-0.595114,-0.690035,-0.274931,-0.591995,-1.487578,-1.108690,-0.402167,0.823232,4
1,319,0.735607,1.352930,-0.775267,0.256260,-0.116184,1.350792,0.837226,1.008786,-0.072005,-0.107102,-0.021574,3
2,516,2.401746,0.403229,1.124700,1.249529,0.266383,-1.039977,-0.987312,2.254318,-0.395969,0.483029,1.386435,3
3,830,-0.470907,0.878080,-1.032019,-0.027532,-0.626274,-1.039977,-1.139357,-0.226146,0.446337,-0.638220,0.447763,1
4,1336,-1.332702,-0.155419,-1.391472,-0.807957,-0.647527,-0.083669,-0.622404,-1.201371,0.316751,-1.228350,-0.866379,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,1367,-0.815625,0.068040,0.149042,-0.240375,0.011338,-0.657454,1.779904,0.266767,-0.395969,3.079604,0.072294,3
476,1054,-0.068735,0.626688,-0.005010,-0.382271,0.160114,-1.039977,0.928453,0.383370,-1.173483,-0.225128,-1.241848,3
477,816,0.850513,-0.099554,-0.415813,0.469103,-0.137438,-0.753085,-0.500769,0.876283,-0.525555,-0.461180,0.072294,3
478,681,-0.183641,-0.434742,-0.210412,-0.240375,0.138860,0.011961,-0.531178,-0.289747,-0.655141,-0.992298,-0.209308,3
479,1383,-0.183641,0.403229,-0.261762,-0.311323,-0.158692,0.872638,1.779904,-0.326848,-0.072005,-0.992298,-0.490910,2

In [34]:
print('valid_table:')
df_valid_table

valid_table:

,index,FixedAcidity,VolatileAcidity,CitricAcid,ResidualSugar,Chlorides,FreeSulfurDioxide,TotalSulfurDioxide,Density,PH,Sulphates,Alcohol,Class
0,852,-0.183641,-0.602337,0.251743,-0.027532,-0.158692,0.968269,2.296856,0.669577,-0.590348,2.430460,-0.678644,2
1,300,-0.470907,0.012176,-1.083370,0.043416,-0.031169,0.394484,-0.075043,-0.130743,0.446337,-0.402167,0.260028,3
2,602,-0.356000,1.716051,-1.391472,0.043416,-0.137438,-0.944346,-0.987312,0.399270,-0.072005,-0.815259,-1.054113,2
3,903,-0.873078,0.347364,-1.083370,2.455641,-0.583766,-0.466193,-0.865676,-0.289747,0.640715,-0.402167,0.353895,4
4,1134,0.103624,-1.384443,0.405794,-0.595114,-0.562513,-0.944346,-0.956903,-0.798561,-0.072005,0.483029,1.292568,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,1453,-0.413454,-0.211283,0.303093,-0.453218,-0.286214,1.063900,1.171725,0.166064,0.640715,-0.461180,-1.335715,2
316,471,0.735607,0.068040,0.765247,-0.098479,-0.137438,0.872638,0.168229,0.134264,-0.719933,0.305990,0.917099,3
317,40,-0.585813,-0.434742,0.457144,2.384693,-0.286214,-0.370562,1.232543,0.558274,0.122373,1.014147,0.072294,2
318,1301,-0.930531,1.855713,-1.032019,-0.382271,0.266383,0.394484,0.320274,-0.406350,1.871778,0.483029,1.198701,3
319,1102,-1.275249,-0.267148,-0.929318,-0.595114,-0.201199,0.203223,-0.500769,-1.445177,0.899886,-0.697233,0.729364,3

### Получаем 3 выборки в датафреймах: тестовую, обучающую и валидационную.

-------------------
## Задание 5 (Task 5)

#### На основе обучающей и тестовой выборки постройте MLP-классификатор. Рассчитайте параметры его эффективности (Accuracy, Precision. Recall, ROC-AUC). Меняя значение параметров классификатора обосновано подберите наиболее удачную MLP-сеть

In [35]:
from sklearn.neural_network import MLPClassifier

In [38]:
clf = MLPClassifier(solver = 'lbfgs', alpha = 0.1, hidden_layer_sizes = (2, 2), random_state = 22222)
clf.fit(df_train_table[Columns], df_train_table['Class'])
res = clf.predict(df_test_table[Columns])

df_test_table['mlp_class'] = res
df_test_table

C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

,index,FixedAcidity,VolatileAcidity,CitricAcid,ResidualSugar,Chlorides,FreeSulfurDioxide,TotalSulfurDioxide,Density,PH,Sulphates,Alcohol,Class,mlp_class
0,1125,0.275983,-1.607903,0.405794,-0.595114,-0.690035,-0.274931,-0.591995,-1.487578,-1.108690,-0.402167,0.823232,4,4
1,319,0.735607,1.352930,-0.775267,0.256260,-0.116184,1.350792,0.837226,1.008786,-0.072005,-0.107102,-0.021574,3,2
2,516,2.401746,0.403229,1.124700,1.249529,0.266383,-1.039977,-0.987312,2.254318,-0.395969,0.483029,1.386435,3,4
3,830,-0.470907,0.878080,-1.032019,-0.027532,-0.626274,-1.039977,-1.139357,-0.226146,0.446337,-0.638220,0.447763,1,3
4,1336,-1.332702,-0.155419,-1.391472,-0.807957,-0.647527,-0.083669,-0.622404,-1.201371,0.316751,-1.228350,-0.866379,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,1367,-0.815625,0.068040,0.149042,-0.240375,0.011338,-0.657454,1.779904,0.266767,-0.395969,3.079604,0.072294,3,2
476,1054,-0.068735,0.626688,-0.005010,-0.382271,0.160114,-1.039977,0.928453,0.383370,-1.173483,-0.225128,-1.241848,3,2
477,816,0.850513,-0.099554,-0.415813,0.469103,-0.137438,-0.753085,-0.500769,0.876283,-0.525555,-0.461180,0.072294,3,3
478,681,-0.183641,-0.434742,-0.210412,-0.240375,0.138860,0.011961,-0.531178,-0.289747,-0.655141,-0.992298,-0.209308,3,2
479,1383,-0.183641,0.403229,-0.261762,-0.311323,-0.158692,0.872638,1.779904,-0.326848,-0.072005,-0.992298,-0.490910,2,2

-------------------
## Задание 6 (Task 6)

-------------------
## Задание 7 (Task 7)

-------------------
## Задание 8 (Task 8)