# Лабораторная работа №5 (Laboratory work 5)
### Построение нейронной сети (сравнение с методом свободных векторов) - исследование красного вина (Neural network construction (comparison with the free vector method) - Red Wine Research)

--------------------------------------
### Эпилог (Epilogue):
#### Набор данных относится к красному варианту португальского вина Vinho Verde. Из-за конфиденциальности и логистических проблем доступны только физико-химические (входные данные) и "качество" вина. Также учитываем, что нет дополнительных данных, т.е. о сортах винограда, марке вина, отпускной цене вина и т.д. (The dataset refers to the red variant of the Portuguese wine Vinho Verde. Due to confidentiality and logistical issues, only the physico-chemical (input data) and "quality" of the wine are available. We also take into consideration that there is no additional data, i.e. about grape varieties, wine brand, selling price of wine, etc.)
### Цель (Goal):
#### Данные не стандартизированы, не сбалансированы. Нужно научиться классифицировать данные и сравнить методы: задачу классификации и её после метода главных компонент, сделать вывод о лучшей классификации. (The data is not standardized, not balanced. It is necessary to learn how to classify data and compare methods: the classification task and its main components after the method, to conclude about the best classification.)

-------------------------------------
## Задания 1-2 (Tasks 1-2)
#### Загрузка и анализ исходных данных (Downloading and analyzing input data)

In [4]:
import pandas as pd
df = pd.read_csv('vine.dat', header=None)
df.columns =['FixedAcidity', 'VolatileAcidity', 'CitricAcid', 'ResidualSugar', 'Chlorides', 'FreeSulfurDioxide', 'TotalSulfurDioxide', 'Density', 'PH', 'Sulphates', 'Alcohol', 'Class']
df

,FixedAcidity,VolatileAcidity,CitricAcid,ResidualSugar,Chlorides,FreeSulfurDioxide,TotalSulfurDioxide,Density,PH,Sulphates,Alcohol,Class
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [5]:
print(df['Class'].unique())

[5 6 7 4 8 3]

In [6]:
df['Class'] = df['Class'] - 3
df.dtypes

FixedAcidity          float64
VolatileAcidity       float64
CitricAcid            float64
ResidualSugar         float64
Chlorides             float64
FreeSulfurDioxide     float64
TotalSulfurDioxide    float64
Density               float64
PH                    float64
Sulphates             float64
Alcohol               float64
Class                   int64
dtype: object

-----------------
## Задание 3 (Task 3)
#### Стандартизация (Standardization)

In [7]:
from sklearn import preprocessing
import numpy as np

#### Объявим переменную с названиями всех колонок кроме 'Class' (Declare a variable with the names of all columns except 'Class')

In [8]:
Columns = ['FixedAcidity', 'VolatileAcidity', 'CitricAcid', 'ResidualSugar', 'Chlorides', 'FreeSulfurDioxide', 'TotalSulfurDioxide', 'Density', 'PH', 'Sulphates', 'Alcohol']

In [9]:
scaler_std = preprocessing.StandardScaler()
df[Columns] = scaler_std.fit_transform(df[Columns])
df.dropna()
df

,FixedAcidity,VolatileAcidity,CitricAcid,ResidualSugar,Chlorides,FreeSulfurDioxide,TotalSulfurDioxide,Density,PH,Sulphates,Alcohol,Class
0,-0.528360,0.961877,-1.391472,-0.453218,-0.243707,-0.466193,-0.379133,0.558274,1.288643,-0.579207,-0.960246,2
1,-0.298547,1.967442,-1.391472,0.043416,0.223875,0.872638,0.624363,0.028261,-0.719933,0.128950,-0.584777,2
2,-0.298547,1.297065,-1.186070,-0.169427,0.096353,-0.083669,0.229047,0.134264,-0.331177,-0.048089,-0.584777,2
3,1.654856,-1.384443,1.484154,-0.453218,-0.264960,0.107592,0.411500,0.664277,-0.979104,-0.461180,-0.584777,3
4,-0.528360,0.961877,-1.391472,-0.453218,-0.243707,-0.466193,-0.379133,0.558274,1.288643,-0.579207,-0.960246,2
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,-1.217796,0.403229,-0.980669,-0.382271,0.053845,1.542054,-0.075043,-0.978765,0.899886,-0.461180,0.072294,2
1595,-1.390155,0.123905,-0.877968,-0.240375,-0.541259,2.211469,0.137820,-0.862162,1.353436,0.601055,0.729364,3
1596,-1.160343,-0.099554,-0.723916,-0.169427,-0.243707,1.255161,-0.196679,-0.533554,0.705508,0.542042,0.541630,3
1597,-1.390155,0.654620,-0.775267,-0.382271,-0.264960,1.542054,-0.075043,-0.676657,1.677400,0.305990,-0.209308,2
1598,-1.332702,-1.216849,1.021999,0.752894,-0.434990,0.203223,-0.135861,-0.666057,0.511130,0.010924,0.541630,3

#### Данные стандартизированы и очищены от нулевых значений. (The data is standardized and cleared of zero values.)

## Задание 4 (Task 4)
### Разделяем полученный датафрейм две выборки: обучающую* и тестовую выборки в соотношении 7 к 3 соответственно. (We divide the resulting dataframe into two samples: training* and test samples in a ratio of 7 to 3, respectively.)
##### *Валидационная выборка входит в обучающую и составляет 2 части из всех 10. В данном случае используем ее для вывода по наилучшей классификации между методами. (The validation sample is included in the training and consists of 2 parts out of all 10. In this case, we use it to infer the best classification between the methods.)

In [10]:
col = ['index'] + Columns + ['Class']

In [11]:
from sklearn.model_selection import train_test_split

In [13]:
y = df['Class']
train_table, test_table = train_test_split(df, train_size = 0.7)
train_class, test_class = train_test_split(y, train_size = 0.7)

train_table = train_table.reset_index()
test_table = test_table.reset_index()
train_class = train_class
test_class = test_class

df_test_table = pd.DataFrame(test_table, columns = col)
df_train_table = pd.DataFrame(train_table, columns = col)

print('train_table:')
df_train_table

train_table:

,index,FixedAcidity,VolatileAcidity,CitricAcid,ResidualSugar,Chlorides,FreeSulfurDioxide,TotalSulfurDioxide,Density,PH,Sulphates,Alcohol,Class
0,444,-1.734874,0.235635,-1.340122,-0.595114,-0.711289,-1.039977,-0.591995,-1.773786,1.677400,1.073160,1.949639,4
1,985,-0.528360,0.291499,-1.391472,-0.382271,-0.498751,-0.848716,-1.078539,-0.597155,0.899886,-0.461180,0.823232,3
2,545,0.448342,-0.323013,1.124700,0.043416,0.138860,2.115838,1.810313,0.770280,-1.497447,-0.402167,-1.241848,2
3,831,-1.390155,0.459094,-0.980669,-0.311323,-0.349975,0.011961,-0.683222,-1.582981,1.612607,0.660068,0.635497,3
4,1139,-0.068735,-0.099554,-0.159061,-0.382271,-0.179946,0.011961,1.202134,0.473472,0.187166,-0.107102,-0.866379,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1114,460,0.505795,-0.546472,1.278752,-0.169427,-0.094931,-0.179300,-0.713631,0.452272,0.251958,-0.284141,0.823232,3
1115,1164,0.390889,1.436727,-0.159061,-0.595114,-0.201199,-0.561823,-0.774449,0.091862,-0.136798,0.069937,-0.397043,2
1116,6,-0.241094,0.403229,-1.083370,-0.666062,-0.392483,-0.083669,0.381091,-0.183745,-0.072005,-1.169337,-0.960246,2
1117,1218,-0.068735,-0.714066,0.200392,-0.453218,-0.116184,-0.753085,-0.683222,-0.395750,-0.460762,0.187963,0.166161,3
1118,1011,0.333436,-1.160984,0.200392,-0.382271,0.011338,-0.370562,-0.835267,-0.554754,-0.914312,-0.638220,-0.021574,3

In [14]:
print('test_table:')
df_test_table

test_table:

,index,FixedAcidity,VolatileAcidity,CitricAcid,ResidualSugar,Chlorides,FreeSulfurDioxide,TotalSulfurDioxide,Density,PH,Sulphates,Alcohol,Class
0,218,-0.470907,-0.211283,-0.415813,-0.453218,-0.243707,-0.561823,-0.075043,-0.554754,0.511130,-0.697233,-0.678644,2
1,759,0.275983,-0.602337,-0.313113,-0.027532,0.096353,1.637684,1.262952,0.786180,-0.784726,-0.815259,-1.147981,2
2,368,1.137779,-1.049255,1.278752,0.185312,1.520352,-0.083669,0.867635,1.618302,-0.849519,-0.107102,-0.960246,2
3,804,0.046171,-0.043689,-0.261762,0.114364,-0.073677,-1.135608,-0.865676,0.038861,-0.331177,-0.520193,-0.490910,3
4,149,-0.068735,-0.714066,0.867948,0.185312,0.032592,-0.466193,-0.105452,0.399270,1.418228,-0.284141,0.072294,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,1032,-0.126188,1.632254,-1.391472,1.107633,0.160114,-1.039977,-0.987312,0.950485,0.316751,-0.756246,-0.772512,2
476,1172,0.793060,-0.602337,0.970649,-0.311323,-0.286214,-1.039977,-0.926494,-0.136043,-0.266384,0.483029,1.761904,3
477,317,0.735607,1.352930,-0.775267,0.256260,-0.116184,1.350792,0.837226,1.008786,-0.072005,-0.107102,-0.021574,3
478,1432,-1.390155,-0.490607,-1.391472,-0.666062,-0.966333,-1.231239,-1.078539,-1.243772,1.094265,1.132173,1.198701,3
479,616,0.735607,0.403229,1.176051,-0.169427,-0.179946,1.159531,0.745999,1.565300,1.223850,-0.520193,-0.678644,2

#### Получаем 4 выборки в датафреймах: 2 выборки с признаками и классами (тестовую и обучающую) и 2 выборки только с классами (тестовую и обучающую). (We get 4 samples in dataframes: 2 samples with attributes and classes (test and training) and 2 samples with classes only (test and training).)